# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/zainryan/pre-commit-hooks
    rev: v1.0.1
    hooks:
      - id: clang-format
        args: [ -style=file, -i ]
      - id: clang-tidy
        args: [ --fix, -extra-arg=-ferror-limit=0, --extra-arg=-stdlib=libc++ ]
